' 参考： https://plantuml.com/zh/activity-diagram-beta
@startuml flow1

|#palegreen|省级专责|
start
:创建督察任务;
:选择组长并派发;
|#pink|支撑组|
:组长选择督查组长并派发;
|督查组|
:选择督查组员;
fork
    :（组长）管理违章列表;
fork again
    :（组员）编辑违章问题;
end merge
:生成违章单;
|#gold|责任人员|
repeat
split
:选择需要申诉的问题;
:发起申诉;
|督查组|
:处理申诉;
if (申诉有效?) then (是)
    :上报;
|支撑组|
    :处理申诉;
    if (申诉有效?) then (是)
        :上报;
|省级专责|
        :处理申诉;
        if (申诉有效?) then (是)
            :批复申诉成功;
        else (否)
            :填写驳回理由，标记问题'待整改';
        endif
    else (否)
|支撑组|
        :填写驳回理由，标记问题'待整改';
    end if
else (否)
|督查组|
    :填写驳回理由，标记问题'待整改';
endif

split again
|责任人员|
:选择需要整改的问题;
:提交整改;
|督查组|
:处理整改;
if (整改有效?) then (是)
    :上报;
|支撑组|
    :处理整改;
    if (整改有效?) then (是)
        :批复整改完成;
    else (否)
        :填写驳回理由，标记问题'待整改';
    endif
else (否)
|督查组|
    :填写驳回理由，标记问题'待整改';
endif
|责任人员|
end split
repeat while (并非所有问题皆已'申诉成功'或'整改完成'?)

stop
@enduml