' 参考： https://plantuml.com/zh/class-diagram
@startuml model

class 督察计划 {
    派发状态
    建管单位
    项目名称
    风险内容
    风险等级
    电压等级
    开始时间
    结束时间
}
class 督察任务 {
    施工单位
    监理单位
    所属部门
    督查类型
    督导组组长
}
class 通知单{

}
class 违章问题 {
    问题描述
    问题状态
    问题照片
    违章示例
    违反条例
    违章性质
    违章等级
    计分标准
    是否变更违章等级
    责任单位
    整改期限
    创建人
    创建时间
}

class 任务分配{
    分配时间
    督查组组员
}

class 人员{
    姓名
    所属部门
    所属单位
    联系方式
}

class 整改记录{
    整改时间
    整改说明
    整改审核时间
    整改审核意见
}

class 申诉{
    申诉时间
    申诉提交人
    申诉内容
    申诉附件
    申诉状态
}

class 申诉审核{
    审核时间
    审核人
    是否通过
    驳回理由
}
class 督察人员
class 责任人员

note "整改负责人" as N1
责任人员 .. N1

督察人员 --|> 人员
责任人员 --|> 人员

督察计划 "1" o--right "0..1" 督察任务
督察任务 "1" *-- "0..1" 通知单
通知单 "1" *-- "0..n" 违章问题
督察任务 "1" *-- "1" 任务分配 
任务分配 "1" o-- "1..n" 督察人员
通知单 "1" o-- "1" 责任人员
违章问题 "1" *-- "0..1" 申诉
违章问题 "1" *-- "0..n" 整改记录

申诉 "1" *-- "0..n" 申诉审核
@enduml