' 参考： https://plantuml.com/zh/state-diagram
@startuml stateissue
[*] --> 待整改
待整改 --> 申诉待审核 : 整改负责人提交了申诉
申诉待审核 --> 申诉成功 : 三级审核全部通过
申诉待审核 --> 申诉未成功 : 未全部通过
申诉未成功 --> 待整改
待整改 --> 整改审核中 : 整改负责人提交了整改
整改审核中 --> 整改完成 : 两级审核全部通过
申诉成功 --> [*]
整改完成 --> [*]
@enduml